all:
  hosts:
    192.1.1.1:
  vars:
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    ansible_user: luiscruz
  children:
    ping:
      hosts:
        192.1.1.1:
      vars:
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    ansible_user: luiscruz
      